project:
  type: book
  output-dir: docs

book:
  title: "Estudio panel Educación y Meritocracia"
  author: "Equipo Edumer"
  date: "08/12/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - reporte_metodologico.qmd
    - meritocracia.qmd
    - ciudadania.qmd
    - references.qmd

bibliography: Educacion-meritocracia.bib

format:
  html:
    theme: cosmo
    language: "es"
  pdf:
    documentclass: scrreprt

editor: visual

